[20:04:36] Log dir: data/bus_engine/ourdeltaNone/09-27-24_20.04.36_vpxn
[20:04:36] Generate Data - Soft Q
  0%|                                                                                      | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ehwkang/DDC-DPT/baseline/SAmQ/main.py", line 162, in <module>
    re_dict = run(parser.parse_args())
  File "/home/ehwkang/DDC-DPT/baseline/SAmQ/main.py", line 40, in run
    softq_dict = softq.train(n_epochs=args.n_steps*2, batch_size=args.batch_size, epoch_size=args.epoch_size,
  File "/home/ehwkang/DDC-DPT/baseline/SAmQ/SAmQ/rl/softQ.py", line 59, in train
    self.data = traj_online_rl_dataclass(self.env.get_data(epoch_size, 'expert'))
  File "/home/ehwkang/DDC-DPT/baseline/SAmQ/SAmQ/env/bus_env.py", line 125, in get_data
    temp_a = np.random.choice([0,1], p=self.opt_action(self.s[0]))
  File "/home/ehwkang/DDC-DPT/baseline/SAmQ/SAmQ/env/bus_env.py", line 100, in opt_action
    return self.EP[s0]
IndexError: index 10 is out of bounds for axis 0 with size 10